// stateNameMapping.js
const stateNameMapping = {
    'INAP': 'Andhra Pradesh',
    'INAR': 'Arunachal Pradesh',
    'INAS': 'Assam',
    'INBR': 'Bihar',
    'INCT': 'Chhattisgarh',
    'INDL': 'Delhi',
    'INGA': 'Goa',
    'INGJ': 'Gujarat',
    'INHR': 'Haryana',
    'INHP': 'Himachal Pradesh',
    'INJK': 'Jammu and Kashmir',
    'INJH': 'Jharkhand',
    'INKA': 'Karnataka',
    'INKL': 'Kerala',
    'INLA': 'Ladakh',
    'INLD': 'Lakshadweep',
    'INMP': 'Madhya Pradesh',
    'INMH': 'Maharashtra',
    'INMN': 'Manipur',
    'INML': 'Meghalaya',
    'INMZ': 'Mizoram',
    'INNL': 'Nagaland',
    'INOR': 'Odisha',
    'INPB': 'Punjab',
    'INRJ': 'Rajasthan',
    'INSK': 'Sikkim',
    'INTN': 'Tamil Nadu',
    'INTG': 'Telangana',
    'INTR': 'Tripura',
    'INUP': 'Uttar Pradesh',
    'INUT': 'Uttarakhand',
    'INWB': 'West Bengal',
    'INAN': 'Andaman and Nicobar Islands',
    'INCH': 'Chandigarh',
    'INDN': 'Dadra and Nagar Haveli and Daman and Diu',
    'INPY': 'Puducherry'
};

export default stateNameMapping;
